---
# tasks file for common
- name: Dnf update
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Time zone
  become: true
  shell: "timedatectl | grep 'Time zone' | awk '{print  $3}'"
  register: time_zone
  changed_when: false
  ignore_errors: true

- name: Install Timezone
  become: true
  shell: |
    timedatectl set-timezone "{{ os_time_zone }}"
  changed_when: false
  when:
    - time_zone.stdout != os_time_zone

- name: Install git
  become: true
  dnf:
    name: 'git'
    state: present

- name: Install make
  become: true
  dnf:
    name: 'make'
    state: present

- name: Install readline-devel
  become: true
  dnf:
    name: 'readline-devel'
    state: present

- name: Install ncurses-devel
  become: true
  dnf:
    name: 'ncurses-devel'
    state: present

- name: Install readline-devel
  become: true
  dnf:
    name: 'openssl-devel'
    state: present

- name: Install development tools
  become: true
  dnf:
    name: "@Development tools"
    state: present
    skip_broken: true
